// frontend/src/pages/Dashboard.tsx
import React, { useEffect, useState } from 'react'
import { Card, Row, Col, Spin, Empty } from 'antd'
import ReactECharts from 'echarts-for-react'
import { dashboardApi } from '../api'

const Dashboard: React.FC = () => {
  const [data, setData] = useState<any>(null)
  const [trend, setTrend] = useState<any>({ items: [] })
  const [dist, setDist] = useState<any>({ items: [] })
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    Promise.all([dashboardApi.overview(), dashboardApi.kpiTrend(14), dashboardApi.schemeDistribution()])
      .then(([o, t, d]) => { setData(o); setTrend(t); setDist(d) })
      .finally(() => setLoading(false))
  }, [])

  if (loading || !data) return <div style={{ textAlign: 'center', padding: 80 }}><Spin tip="加载中..." /></div>

  const trendOpt = {
    tooltip: { trigger: 'axis' },
    grid: { left: 40, right: 20, top: 20, bottom: 30 },
    xAxis: { type: 'category', data: (trend.items || []).map((i: any) => i.date.slice(5)) },
    yAxis: { type: 'value', name: '录入数' },
    series: [{
      data: (trend.items || []).map((i: any) => i.count),
      type: 'line', smooth: true, areaStyle: { color: 'rgba(102,126,234,0.25)' },
      lineStyle: { color: '#667eea', width: 2.5 },
      itemStyle: { color: '#764ba2' },
    }],
  }

  const distOpt = {
    tooltip: { trigger: 'item', formatter: '{b}: {c} ({d}%)' },
    legend: { bottom: 0, type: 'scroll' },
    series: [{
      type: 'pie', radius: ['45%', '70%'],
      data: (dist.items || []).map((i: any) => ({ name: `${i.scheme_code} · ${i.scheme_name}`, value: i.def_count })),
      label: { formatter: '{b}\n{d}%' },
      color: ['#667eea', '#764ba2', '#f59e0b', '#52c41a', '#1890ff', '#eb2f96', '#13c2c2', '#fa8c16'],
    }],
  }

  return (
    <div>
      <div className="page-title">
        <span className="page-title-icon" />
        PRCP 组算平台 · 总览
      </div>

      <Row gutter={[16, 16]}>
        {data.kpi.map((k: any, i: number) => (
          <Col xs={24} sm={12} lg={6} key={i}>
            <Card className="kpi-card">
              <div className="kpi-label">{k.label}</div>
              <div className="kpi-value" style={{ color: k.color }}>{k.value} <span style={{ fontSize: 13, color: '#999' }}>{k.unit}</span></div>
            </Card>
          </Col>
        ))}
      </Row>

      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        <Col xs={24} lg={14}>
          <Card title="近 14 天指标值录入趋势">
            {trend.items?.length ? <ReactECharts option={trendOpt} style={{ height: 320 }} /> : <Empty />}
          </Card>
        </Col>
        <Col xs={24} lg={10}>
          <Card title="指标方案下指标定义分布">
            {dist.items?.length ? <ReactECharts option={distOpt} style={{ height: 320 }} /> : <Empty description="暂无数据" />}
          </Card>
        </Col>
      </Row>
    </div>
  )
}

export default Dashboard

// vue-poC/src/views/dashboard/Index.vue
<template>
  <div class="dash-page" v-loading="loading">
    <div class="page-header">
      <h2>驾驶舱</h2>
      <p class="desc">账户册 / 报表 / 指标 / 评分规则 总览（ECharts）</p>
      <span class="data-date" v-if="latestDate">最新数据日期：{{ latestDate }}</span>
    </div>

    <!-- 8 KPI 卡片 -->
    <el-row :gutter="14" class="kpi-row">
      <el-col :span="6" v-for="(k, i) in kpis" :key="i">
        <el-card shadow="hover" class="kpi-card" :style="{ borderTop: `3px solid ${k.color}` }">
          <div class="kpi-label">{{ k.label }}</div>
          <div class="kpi-value" :style="{ color: k.color }">{{ formatNum(k.value) }}</div>
          <div class="kpi-unit">{{ k.unit }}</div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 4 个图表 -->
    <el-row :gutter="14" class="chart-row">
      <el-col :span="12">
        <el-card shadow="never" header="📈 指标值录入趋势（近 14 天）">
          <v-chart v-if="!loading && trend.length" :options="trendOption" :autoresize="true" style="height:280px" />
          <div v-else class="chart-placeholder">{{ loading ? '加载中...' : '暂无趋势数据' }}</div>
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card shadow="never" header="🥧 指标方案定义分布（TOP 8）">
          <v-chart v-if="!loading && schemes.length" :options="schemeOption" :autoresize="true" style="height:280px" />
          <div v-else class="chart-placeholder">{{ loading ? '加载中...' : '暂无方案分布' }}</div>
        </el-card>
      </el-col>
    </el-row>

    <el-row :gutter="14" class="chart-row">
      <el-col :span="14">
        <el-card shadow="never" header="🏆 Top10 指标（按当前绝对值）">
          <v-chart v-if="!loading && topKpis.length" :options="topOption" :autoresize="true" style="height:300px" />
          <div v-else class="chart-placeholder">{{ loading ? '加载中...' : '暂无 Top10 数据' }}</div>
        </el-card>
      </el-col>
      <el-col :span="10">
        <el-card shadow="never" header="📋 指标试算得分排行">
          <el-table :data="scoredList" border stripe size="small" max-height="280">
              <el-table-column type="index" label="排名" width="60" align="center" />
              <el-table-column prop="kpiCode" label="编码" width="100" />
              <el-table-column prop="kpiName" label="指标" />
              <el-table-column prop="score" label="得分" width="80" align="center">
                <template #default="{ row }">
                  <el-tag :type="row.score >= 80 ? 'success' : (row.score >= 60 ? 'warning' : 'danger')">
                    {{ row.score }}
                  </el-tag>
                </template>
              </el-table-column>
            </el-table>
        </el-card>
      </el-col>
    </el-row>
  </div>
</template>

<script>
import { dashboardApi } from '@/api/dashboard'
import VChart from 'vue-echarts'
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/pie'
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/title'
import 'echarts/lib/component/grid'

export default {
  name: 'DashboardIndex',
  components: { VChart },
  data() {
    return {
      loading: false,
      kpis: [],
      latestDate: null,
      trend: [],
      schemes: [],
      topKpis: [],
      CITIC_RED: '#C7000B'
    }
  },
  computed: {
    trendOption() {
      return {
        tooltip: { trigger: 'axis' },
        grid: { left: 40, right: 20, top: 20, bottom: 30 },
        xAxis: { type: 'category', data: this.trend.map(t => t.d), axisLabel: { fontSize: 11 } },
        yAxis: { type: 'value' },
        series: [{
          name: '指标值录入', type: 'line', smooth: true,
          data: this.trend.map(t => t.n),
          itemStyle: { color: this.CITIC_RED },
          areaStyle: { color: 'rgba(199, 0, 11, 0.15)' }
        }]
      }
    },
    schemeOption() {
      return {
        tooltip: { trigger: 'item', formatter: '{b}<br/>{c} 个指标 ({d}%)' },
        legend: { orient: 'vertical', right: 10, top: 'middle', textStyle: { fontSize: 11 } },
        series: [{
          name: '指标分布', radius: ['45%', '70%'], center: ['38%', '50%'],
          type: 'pie',
          data: this.schemes.map((s, i) => ({
            name: s.schemeName || s.schemeCode,
            value: s.defCount,
            itemStyle: { color: ['#C7000B', '#A31A1F', '#E84E4E', '#D71B1B', '#C8102E',
                                  '#DC2626', '#991B1B', '#7F1D1D'][i % 8] }
          })),
          label: { formatter: '{b}\n{c}', fontSize: 11 }
        }]
      }
    },
    topOption() {
      const data = this.topKpis.slice(0, 10)
      return {
        tooltip: { trigger: 'axis', axisPointer: { type: 'shadow' } },
        grid: { left: 110, right: 30, top: 20, bottom: 30 },
        xAxis: { type: 'value' },
        yAxis: { type: 'category', data: data.map(k => `${k.kpiCode} ${k.kpiName}`), axisLabel: { fontSize: 11 } },
        series: [{
          name: '当前值', type: 'bar',
          data: data.map((k, i) => ({
            value: k.currentValue,
            itemStyle: {
              color: i === 0 ? '#C7000B' : (i === 1 ? '#A31A1F' : (i === 2 ? '#E84E4E' : '#D71B1B'))
            }
          })),
          label: { show: true, position: 'right', formatter: (p) => Number(p.value).toFixed(2) }
        }]
      }
    },
    scoredList() {
      return this.topKpis.filter(k => k.score != null).slice(0, 10)
    }
  },
  async mounted() {
    this.loading = true
    try {
      const [ov, trend, dist, top] = await Promise.all([
        dashboardApi.overview(),
        dashboardApi.kpiTrend(14),
        dashboardApi.schemeDistribution(),
        dashboardApi.topKpis()
      ])
      this.kpis = ov.kpi || []
      this.latestDate = ov.latest_data_date
      this.trend = trend.items || []
      this.schemes = dist.items || []
      this.topKpis = top.items || []
    } finally { this.loading = false }
  },
  methods: {
    formatNum(v) {
      if (v == null) return 0
      const n = Number(v)
      if (Number.isNaN(n)) return v
      return n.toLocaleString('zh-CN')
    }
  }
}
</script>

<style scoped>
.dash-page { padding: 0; }
.page-header { background:#fff; padding:16px 24px; margin-bottom:16px; border-bottom:1px solid #f0f0f0; position:relative; }
.page-header h2 { margin:0; }
.page-header .desc { color:#999; font-size:13px; margin:4px 0 0; }
.data-date { position:absolute; right:24px; top:24px; color:#C7000B; font-size:13px; }
.kpi-row { margin:0 16px 14px; }
.kpi-card { text-align:center; padding:6px 0; background:#fff; }
.kpi-label { color:#888; font-size:13px; }
.kpi-value { font-size:30px; font-weight:bold; margin:4px 0; line-height:1.1; }
.kpi-unit { color:#aaa; font-size:12px; }
.chart-row { margin:0 16px 14px; }
.echarts { width:100%; }
.chart-placeholder { padding: 120px 0; text-align: center; color: #999; font-size: 13px; }
</style>
