// frontend/src/pages/Reports.tsx
import React, { useEffect, useMemo, useState } from 'react'
import {
  Card, Row, Col, Tree, Form, Input, Select, Button, Table, Space, Tag,
  Modal, message, Spin, Empty, Tabs, InputNumber, Popconfirm,
} from 'antd'
import {
  PlusOutlined, EditOutlined, DeleteOutlined, ReloadOutlined,
  ApartmentOutlined, FolderOutlined, FileTextOutlined,
} from '@ant-design/icons'
import type { DataNode } from 'antd/es/tree'
import type { ColumnsType } from 'antd/es/table'
import { reportsApi, coaApi } from '../api'

const REPORT_TYPES = [
  { value: 'BALANCE', label: '资产负债表', color: 'blue' },
  { value: 'INCOME', label: '损益表', color: 'green' },
  { value: 'CASHFLOW', label: '现金流量表', color: 'cyan' },
  { value: 'INDICATOR', label: '关键指标表', color: 'purple' },
  { value: 'RISK', label: 'RWA 报表', color: 'red' },
  { value: 'LIQUIDITY', label: '流动性报表', color: 'orange' },
]

const Reports: React.FC = () => {
  const [reports, setReports] = useState<any[]>([])
  const [schemes, setSchemes] = useState<any[]>([])
  const [activeReport, setActiveReport] = useState<number | null>(null)
  const [tree, setTree] = useState<any[]>([])
  const [selectedKey, setSelectedKey] = useState<string | null>(null)
  const [selectedItem, setSelectedItem] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [rptModalOpen, setRptModalOpen] = useState(false)
  const [editingRpt, setEditingRpt] = useState<any>(null)
  const [itemModalOpen, setItemModalOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<any>(null)
  const [rptForm] = Form.useForm()
  const [itemForm] = Form.useForm()

  const loadReports = async () => {
    setLoading(true)
    try {
      const [r, s] = await Promise.all([reportsApi.list({}), coaApi.listSchemes()])
      setReports(r.items || [])
      setSchemes(s.items || [])
      if (!activeReport && r.items?.length) setActiveReport(r.items[0].id)
    } catch { message.error('报表加载失败') }
    finally { setLoading(false) }
  }
  useEffect(() => { loadReports() }, [])

  useEffect(() => {
    if (!activeReport) return
    setLoading(true)
    reportsApi.treeItems(activeReport).then((r) => {
      setTree(r.items || [])
      setSelectedKey(null); setSelectedItem(null)
    }).catch(() => message.error('表项加载失败'))
      .finally(() => setLoading(false))
  }, [activeReport])

  const onSelect = (keys: React.Key[]) => {
    if (!keys.length) { setSelectedKey(null); setSelectedItem(null); return }
    const k = String(keys[0])
    setSelectedKey(k)
    const find = (nodes: any[]): any => {
      for (const n of nodes) {
        if (n.key === k) return n
        if (n.children?.length) { const c = find(n.children); if (c) return c }
      }
      return null
    }
    setSelectedItem(find(tree))
  }

  // 报表 CRUD
  const onCreateRpt = () => {
    setEditingRpt(null)
    rptForm.resetFields()
    rptForm.setFieldsValue({ status: 'ACTIVE' })
    setRptModalOpen(true)
  }
  const onEditRpt = (r: any) => {
    setEditingRpt(r)
    rptForm.setFieldsValue(r)
    setRptModalOpen(true)
  }
  const onSaveRpt = async () => {
    const v = await rptForm.validateFields()
    try {
      if (editingRpt) {
        await reportsApi.update(editingRpt.id, v)
        message.success('已更新')
      } else {
        const r = await reportsApi.create(v)
        message.success('已创建')
        setActiveReport(r.id)
      }
      setRptModalOpen(false)
      loadReports()
    } catch (e: any) { message.error(e?.response?.data?.detail || '保存失败') }
  }

  // 表项 CRUD
  const onCreateItem = (parent?: any) => {
    setEditingItem(null)
    itemForm.resetFields()
    itemForm.setFieldsValue({
      report_id: activeReport,
      parent_id: parent?.id || null,
      data_type: 'DECIMAL',
      sort_order: 0,
      status: 'ACTIVE',
      coa_node_ids: [],
    })
    setItemModalOpen(true)
  }
  const onEditItem = (n: any) => {
    setEditingItem(n)
    itemForm.setFieldsValue({
      report_id: activeReport,
      item_code: n.code,
      item_name: n.name,
      parent_id: n.parent_id || null,
      data_type: n.data_type || 'DECIMAL',
      formula: n.formula,
      coa_node_ids: n.coa_node_ids || [],
      sort_order: n.sort_order,
      status: n.status,
    })
    setItemModalOpen(true)
  }
  const onSaveItem = async () => {
    const v = await itemForm.validateFields()
    try {
      if (editingItem) {
        await reportsApi.updateItem(editingItem.id, v)
        message.success('已更新')
      } else {
        await reportsApi.createItem(v)
        message.success('已创建')
      }
      setItemModalOpen(false)
      reportsApi.treeItems(activeReport!).then((r) => setTree(r.items || []))
      loadReports()
    } catch (e: any) { message.error(e?.response?.data?.detail || '保存失败') }
  }

  const treeData: DataNode[] = useMemo(() => {
    const toNode = (n: any): DataNode => ({
      key: n.key,
      title: <span><Tag color="blue" style={{ marginRight: 4 }}>{n.level}</Tag>{n.title}</span>,
      children: n.children?.length ? n.children.map(toNode) : undefined,
    })
    return tree.map(toNode)
  }, [tree])

  const rptCols: ColumnsType<any> = [
    { title: '编码', dataIndex: 'report_code', width: 120, render: (c) => <code>{c}</code> },
    { title: '名称', dataIndex: 'report_name', ellipsis: true },
    { title: '类型', dataIndex: 'report_type', width: 110,
      render: (t) => <Tag color={REPORT_TYPES.find((x) => x.value === t)?.color}>{REPORT_TYPES.find((x) => x.value === t)?.label || t}</Tag> },
    { title: '关联账户册', dataIndex: 'scheme_name', width: 140 },
    { title: '表项数', dataIndex: 'item_count', width: 90, render: (n) => <Tag>{n || 0}</Tag> },
    { title: '状态', dataIndex: 'status', width: 80, render: (s) => <Tag color={s === 'ACTIVE' ? 'green' : 'default'}>{s}</Tag> },
    {
      title: '操作', width: 140, fixed: 'right' as const,
      render: (_, r) => (
        <Space size="small">
          <Button size="small" icon={<EditOutlined />} onClick={() => onEditRpt(r)}>编辑</Button>
          <Popconfirm title="确认删除报表及其所有表项？" onConfirm={async () => {
            await reportsApi.delete(r.id)
            message.success('已删除')
            if (activeReport === r.id) setActiveReport(null)
            loadReports()
          }}><Button size="small" danger icon={<DeleteOutlined />}>删除</Button></Popconfirm>
        </Space>
      ),
    },
  ]

  return (
    <Spin spinning={loading}>
      <div className="page-title">
        <span className="page-title-icon" />
        <span>报表表项管理 <span style={{ color: '#999', fontSize: 14, fontWeight: 'normal' }}>· 6 类报表 + 树形表项</span></span>
      </div>

      <Card
        bordered={false}
        bodyStyle={{ padding: 0 }}
        title={
          <Tabs
            activeKey={activeReport ? String(activeReport) : ''}
            onChange={(k) => setActiveReport(Number(k))}
            items={reports.map((r) => ({
              key: String(r.id),
              label: <span>{r.report_name} <Tag color="blue">{r.item_count}</Tag></span>,
            }))}
            tabBarExtraContent={
              <Space>
                <Button size="small" type="primary" icon={<PlusOutlined />} onClick={onCreateRpt}>新增报表</Button>
                <Button size="small" icon={<ReloadOutlined />} onClick={loadReports} />
              </Space>
            }
          />
        }
      >
        <Row style={{ minHeight: 520 }}>
          <Col span={9} style={{ borderRight: '1px solid #f0f0f0', padding: 12 }}>
            <div style={{ marginBottom: 8, color: '#666', fontSize: 13 }}>
              <FolderOutlined style={{ marginRight: 6 }} /> 报表列表（{reports.length}）
            </div>
            <Table size="small" rowKey="id" dataSource={reports} columns={rptCols}
              pagination={false} scroll={{ y: 460 }}
              onRow={(r) => ({ onClick: () => setActiveReport(r.id), style: { cursor: 'pointer', background: r.id === activeReport ? '#e6f4ff' : undefined } })}
            />
          </Col>

          <Col span={6} style={{ borderRight: '1px solid #f0f0f0', padding: 12, background: '#fafafa' }}>
            <div style={{ marginBottom: 8, color: '#666', fontSize: 13, display: 'flex', justifyContent: 'space-between' }}>
              <span><ApartmentOutlined style={{ marginRight: 6 }} />表项树</span>
              <Button size="small" type="primary" icon={<PlusOutlined />} onClick={() => onCreateItem()}>新增根表项</Button>
            </div>
            {treeData.length ? (
              <Tree treeData={treeData} defaultExpandAll showLine blockNode
                selectedKeys={selectedKey ? [selectedKey] : []} onSelect={onSelect} />
            ) : <Empty description="请先选择报表" />}
          </Col>

          <Col span={9} style={{ padding: 16 }}>
            {selectedItem ? (
              <div>
                <div style={{ marginBottom: 12, color: '#666' }}><FileTextOutlined style={{ marginRight: 6 }} />表项详情</div>
                <Form layout="vertical">
                  <Form.Item label="表项编码"><Input value={selectedItem.code} disabled /></Form.Item>
                  <Form.Item label="表项名称"><Input value={selectedItem.name} disabled /></Form.Item>
                  <Row gutter={16}>
                    <Col span={12}><Form.Item label="层级"><Input value={selectedItem.level} disabled /></Form.Item></Col>
                    <Col span={12}><Form.Item label="数据类型"><Tag>{selectedItem.data_type}</Tag></Form.Item></Col>
                  </Row>
                  <Form.Item label="计算公式"><Input.TextArea value={selectedItem.formula || '（无）'} disabled rows={2} /></Form.Item>
                  <Form.Item label="关联账户册节点 ID">
                    <Input value={(selectedItem.coa_node_ids || []).join(', ') || '（无）'} disabled />
                  </Form.Item>
                  <Form.Item label="物化路径"><Input.TextArea value={selectedItem.path} disabled rows={2} /></Form.Item>
                  <Space>
                    <Button type="primary" icon={<EditOutlined />} onClick={() => onEditItem(selectedItem)}>编辑</Button>
                    <Button icon={<PlusOutlined />} onClick={() => onCreateItem(selectedItem)}>新增子表项</Button>
                    <Popconfirm title="删除该表项及其所有子孙？" onConfirm={async () => {
                      await reportsApi.deleteItem(selectedItem.id)
                      message.success('已删除')
                      reportsApi.treeItems(activeReport!).then((r) => setTree(r.items || []))
                      loadReports()
                      setSelectedKey(null); setSelectedItem(null)
                    }}><Button danger icon={<DeleteOutlined />}>删除</Button></Popconfirm>
                  </Space>
                </Form>
              </div>
            ) : <Empty description="请选择树中表项" />}
          </Col>
        </Row>
      </Card>

      <Modal title={editingRpt ? '编辑报表' : '新增报表'} open={rptModalOpen}
        onCancel={() => setRptModalOpen(false)} onOk={onSaveRpt} width={520}>
        <Form form={rptForm} layout="vertical">
          <Row gutter={16}>
            <Col span={12}><Form.Item name="report_code" label="报表编码" rules={[{ required: true }]}><Input placeholder="RPT_BS" /></Form.Item></Col>
            <Col span={12}><Form.Item name="report_name" label="报表名称" rules={[{ required: true }]}><Input /></Form.Item></Col>
          </Row>
          <Form.Item name="report_type" label="报表类型" rules={[{ required: true }]}>
            <Select options={REPORT_TYPES.map((t) => ({ value: t.value, label: t.label }))} />
          </Form.Item>
          <Form.Item name="scheme_id" label="关联账户册方案" rules={[{ required: true }]}>
            <Select options={schemes.map((s) => ({ value: s.id, label: `${s.scheme_code} - ${s.scheme_name}` }))} />
          </Form.Item>
          <Form.Item name="status" label="状态" initialValue="ACTIVE">
            <Select options={[{ value: 'ACTIVE', label: 'ACTIVE' }, { value: 'INACTIVE', label: 'INACTIVE' }]} />
          </Form.Item>
          <Form.Item name="description" label="描述"><Input.TextArea rows={2} /></Form.Item>
        </Form>
      </Modal>

      <Modal title={editingItem ? '编辑表项' : '新增表项'} open={itemModalOpen}
        onCancel={() => setItemModalOpen(false)} onOk={onSaveItem} width={560}>
        <Form form={itemForm} layout="vertical">
          <Form.Item name="report_id" hidden><Input /></Form.Item>
          <Row gutter={16}>
            <Col span={12}><Form.Item name="item_code" label="表项编码" rules={[{ required: true }]}><Input /></Form.Item></Col>
            <Col span={12}><Form.Item name="item_name" label="表项名称" rules={[{ required: true }]}><Input /></Form.Item></Col>
          </Row>
          <Row gutter={16}>
            <Col span={8}><Form.Item name="parent_id" label="父表项 ID"><InputNumber style={{ width: '100%' }} /></Form.Item></Col>
            <Col span={8}><Form.Item name="data_type" label="数据类型"><Select options={[{ value: 'DECIMAL', label: 'DECIMAL' }, { value: 'INT', label: 'INT' }, { value: 'TEXT', label: 'TEXT' }]} /></Form.Item></Col>
            <Col span={8}><Form.Item name="sort_order" label="排序"><InputNumber style={{ width: '100%' }} /></Form.Item></Col>
          </Row>
          <Form.Item name="formula" label="计算公式">
            <Input.TextArea rows={2} placeholder="如：rpt:001001 / rpt:001002" />
          </Form.Item>
          <Form.Item name="coa_node_ids" label="关联账户册节点 ID（多选，逗号分隔）">
            <Select mode="tags" placeholder="输入节点 ID 后回车" tokenSeparators={[',']} />
          </Form.Item>
          <Form.Item name="status" label="状态" initialValue="ACTIVE">
            <Select options={[{ value: 'ACTIVE', label: 'ACTIVE' }, { value: 'INACTIVE', label: 'INACTIVE' }]} />
          </Form.Item>
        </Form>
      </Modal>
    </Spin>
  )
}

export default Reports

// vue-poC/src/views/reports/Index.vue
<template>
  <div class="rpt-page">
    <div class="page-header">
      <h2>报表表项管理</h2>
      <p class="desc">报表定义 + 表项树（6 类报表：资产负债表/损益表/现金流/指标/风险/流动性）</p>
    </div>

    <!-- 上半：报表定义列表 -->
    <el-card class="filter-card">
      <el-row :gutter="16" type="flex" align="middle">
        <el-col :span="5">
          <el-select v-model="filter.reportType" placeholder="报表类型" clearable @change="loadReports">
            <el-option v-for="t in REPORT_TYPES" :label="t.label" :value="t.value" :key="t.value" />
          </el-select>
        </el-col>
        <el-col :span="5">
          <el-select v-model="filter.schemeId" placeholder="账户册方案" clearable filterable @change="loadReports">
            <el-option v-for="s in schemes" :key="s.id"
                       :label="`${s.schemeCode} | ${s.schemeName}`" :value="s.id" />
          </el-select>
        </el-col>
        <el-col :span="6">
          <el-input v-model="filter.keyword" placeholder="报表编码/名称" clearable @keyup.enter.native="loadReports" />
        </el-col>
        <el-col :span="8">
          <el-button type="primary" icon="el-icon-search" @click="loadReports">查询</el-button>
          <el-button icon="el-icon-refresh-left" @click="onReset">重置</el-button>
          <el-button type="danger" icon="el-icon-plus" @click="onAddReport">新增报表</el-button>
        </el-col>
      </el-row>
    </el-card>

    <el-card class="table-card" v-loading="loading">
      <el-table :data="reports" border stripe>
        <el-table-column prop="reportCode" label="报表编码" width="120" />
        <el-table-column prop="reportName" label="报表名称" />
        <el-table-column label="类型" width="100" align="center">
          <template #default="{ row }">
            <el-tag :type="typeTagType(row.reportType)" size="mini">{{ typeLabel(row.reportType) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column prop="schemeName" label="关联方案" width="180" />
        <el-table-column prop="itemCount" label="表项数" width="80" align="center" />
        <el-table-column label="操作" width="260" align="center">
          <template #default="{ row }">
            <el-button type="text" @click="viewItems(row)">📋 表项</el-button>
            <el-button type="text" @click="onEditReport(row)">编辑</el-button>
            <el-button type="text" style="color:#f56c6c;" @click="onDeleteReport(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 新增/编辑报表 -->
    <el-dialog :title="editingReport ? '编辑报表' : '新增报表'" :visible.sync="modalVisible" width="560px">
      <el-form :model="reportForm" :rules="reportRules" ref="reportFormRef" label-width="100px">
        <el-form-item label="报表编码" prop="reportCode"><el-input v-model="reportForm.reportCode" /></el-form-item>
        <el-form-item label="报表名称" prop="reportName"><el-input v-model="reportForm.reportName" /></el-form-item>
        <el-form-item label="报表类型" prop="reportType">
          <el-select v-model="reportForm.reportType" style="width:100%">
            <el-option v-for="t in REPORT_TYPES" :label="t.label" :value="t.value" :key="t.value" />
          </el-select>
        </el-form-item>
        <el-form-item label="账户册方案" prop="schemeId">
          <el-select v-model="reportForm.schemeId" style="width:100%" filterable>
            <el-option v-for="s in schemes" :key="s.id"
                       :label="`${s.schemeCode} | ${s.schemeName}`" :value="s.id" />
          </el-select>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="reportForm.description" type="textarea" :rows="2" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="modalVisible=false">取消</el-button>
        <el-button type="primary" :loading="submitting" @click="onSubmitReport">提交</el-button>
      </template>
    </el-dialog>

    <!-- 表项树弹窗 -->
    <el-dialog :title="`表项管理 - ${currentReport?.reportName || ''}`"
               :visible.sync="itemsModalVisible" width="780px" top="5vh">
      <el-row :gutter="12">
        <el-col :span="16">
          <el-table :data="itemsTree" row-key="id" border default-expand-all
                    :tree-props="{ children: 'children' }" v-loading="itemsLoading" max-height="500">
            <el-table-column prop="itemCode" label="编码" width="120" />
            <el-table-column prop="itemName" label="名称" />
            <el-table-column prop="dataType" label="类型" width="80" align="center" />
            <el-table-column prop="formula" label="公式" show-overflow-tooltip />
            <el-table-column label="操作" width="160" align="center">
              <template #default="{ row }">
                <el-button type="text" size="mini" @click="onAddItemChild(row)">+ 子项</el-button>
                <el-button type="text" size="mini" @click="onEditItem(row)">编辑</el-button>
                <el-button type="text" size="mini" style="color:#f56c6c;" @click="onDeleteItem(row)">删除</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-col>
        <el-col :span="8">
          <el-card shadow="never" class="add-card">
            <div slot="header"><strong>新增表项</strong></div>
            <el-form :model="itemForm" label-width="80px" size="small">
              <el-form-item label="父表项">
                <el-cascader v-model="itemForm.parentPath"
                             :options="cascaderOpts" :props="{ checkStrictly:true, value:'id', label:'itemName' }"
                             clearable change-on-select placeholder="根节点" />
              </el-form-item>
              <el-form-item label="编码"><el-input v-model="itemForm.itemCode" /></el-form-item>
              <el-form-item label="名称"><el-input v-model="itemForm.itemName" /></el-form-item>
              <el-form-item label="数据类型">
                <el-select v-model="itemForm.dataType" style="width:100%">
                  <el-option label="DECIMAL" value="DECIMAL" />
                  <el-option label="PERCENT" value="PERCENT" />
                  <el-option label="INTEGER" value="INTEGER" />
                  <el-option label="TEXT" value="TEXT" />
                </el-select>
              </el-form-item>
              <el-form-item label="公式">
                <el-input v-model="itemForm.formula" type="textarea" :rows="2" placeholder="A+B-C" />
              </el-form-item>
              <el-form-item label="描述">
                <el-input v-model="itemForm.description" type="textarea" :rows="2" />
              </el-form-item>
              <el-button type="danger" icon="el-icon-plus" size="small" :loading="submitting"
                         style="width:100%" @click="onSubmitItem">新增到树</el-button>
            </el-form>
          </el-card>
        </el-col>
      </el-row>
    </el-dialog>
  </div>
</template>

<script>
import { reportsApi } from '@/api/reports'
import { coaApi } from '@/api/coa'

export default {
  name: 'RptIndex',
  data() {
    return {
      REPORT_TYPES: [
        { value: 'BALANCE', label: '资产负债表' },
        { value: 'INCOME', label: '损益表' },
        { value: 'CASHFLOW', label: '现金流量表' },
        { value: 'INDICATOR', label: '指标表' },
        { value: 'RISK', label: '风险表' },
        { value: 'LIQUIDITY', label: '流动性表' }
      ],
      schemes: [],
      filter: { reportType: null, schemeId: null, keyword: '' },
      reports: [],
      loading: false,

      modalVisible: false,
      editingReport: null,
      reportForm: { reportCode: '', reportName: '', reportType: 'BALANCE', schemeId: null, description: '' },
      reportRules: {
        reportCode: [{ required: true, message: '请输入编码' }],
        reportName: [{ required: true, message: '请输入名称' }]
      },
      submitting: false,

      itemsModalVisible: false,
      currentReport: null,
      itemsTree: [],
      itemsLoading: false,
      itemForm: { parentPath: [], itemCode: '', itemName: '', dataType: 'DECIMAL', formula: '', description: '' }
    }
  },
  computed: {
    cascaderOpts() {
      const toOpt = n => ({ id: n.id, itemName: `${n.itemCode} ${n.itemName}`, children: (n.children || []).map(toOpt) })
      return this.itemsTree.map(toOpt)
    }
  },
  async mounted() {
    this.schemes = await coaApi.listSchemes()
    if (this.schemes.length) {
      this.filter.schemeId = this.schemes[0].id
      this.loadReports()
    }
  },
  methods: {
    typeLabel(t) { return (this.REPORT_TYPES.find(x => x.value === t) || {}).label || t },
    typeTagType(t) {
      return { BALANCE: 'danger', INCOME: 'warning', CASHFLOW: 'success',
               INDICATOR: '', RISK: 'info', LIQUIDITY: '' }[t] || ''
    },
    async loadReports() {
      this.loading = true
      try { this.reports = await reportsApi.list({ report_type: this.filter.reportType, scheme_id: this.filter.schemeId, keyword: this.filter.keyword }) }
      finally { this.loading = false }
    },
    onReset() { this.filter = { reportType: null, schemeId: this.filter.schemeId, keyword: '' }; this.loadReports() },
    onAddReport() {
      this.editingReport = null
      this.reportForm = { reportCode: '', reportName: '', reportType: 'BALANCE', schemeId: this.filter.schemeId, description: '' }
      this.modalVisible = true
    },
    onEditReport(row) {
      this.editingReport = row
      this.reportForm = { ...row }
      this.modalVisible = true
    },
    async onSubmitReport() {
      await this.$refs.reportFormRef.validate()
      this.submitting = true
      try {
        if (this.editingReport) await reportsApi.update(this.editingReport.id, this.reportForm)
        else await reportsApi.create(this.reportForm)
        this.$message.success('保存成功')
        this.modalVisible = false
        this.loadReports()
      } finally { this.submitting = false }
    },
    onDeleteReport(row) {
      this.$confirm(`确认删除 [${row.reportCode}] ${row.reportName}？`, '提示', { type: 'warning' })
        .then(async () => { await reportsApi.delete(row.id); this.$message.success('删除成功'); this.loadReports() })
        .catch(() => {})
    },
    async viewItems(row) {
      this.currentReport = row
      this.itemsModalVisible = true
      await this.loadItems()
    },
    async loadItems() {
      this.itemsLoading = true
      try { this.itemsTree = await reportsApi.listItems(this.currentReport.id) }
      finally { this.itemsLoading = false }
    },
    onAddItemChild(parent) {
      this.itemForm = { parentPath: [parent.id], itemCode: '', itemName: '', dataType: 'DECIMAL', formula: '', description: '' }
    },
    onEditItem(row) {
      this.$prompt(`修改 [${row.itemCode}] 名称：`, '编辑表项', { inputValue: row.itemName })
        .then(async ({ value }) => {
          await reportsApi.updateItem(row.id, { ...row, itemName: value })
          this.$message.success('已更新'); this.loadItems()
        }).catch(() => {})
    },
    async onSubmitItem() {
      if (!this.itemForm.itemCode || !this.itemForm.itemName) return this.$message.warning('请输入编码和名称')
      this.submitting = true
      try {
        await reportsApi.createItem({
          reportId: this.currentReport.id,
          itemCode: this.itemForm.itemCode,
          itemName: this.itemForm.itemName,
          dataType: this.itemForm.dataType,
          formula: this.itemForm.formula,
          description: this.itemForm.description,
          parentId: this.itemForm.parentPath.length ? this.itemForm.parentPath[this.itemForm.parentPath.length - 1] : null
        })
        this.$message.success('已新增')
        this.itemForm = { parentPath: [], itemCode: '', itemName: '', dataType: 'DECIMAL', formula: '', description: '' }
        await this.loadItems()
        // 刷新 item_count
        this.loadReports()
      } finally { this.submitting = false }
    },
    onDeleteItem(row) {
      this.$confirm(`确认删除 [${row.itemCode}] ${row.itemName}？`, '提示', { type: 'warning' })
        .then(async () => { await reportsApi.deleteItem(row.id); this.$message.success('已删除'); this.loadItems(); this.loadReports() })
        .catch(() => {})
    }
  }
}
</script>

<style scoped>
.rpt-page { padding: 0; }
.page-header { background:#fff; padding:16px 24px; margin-bottom:16px; border-bottom:1px solid #f0f0f0; }
.page-header h2 { margin:0; }
.page-header .desc { color:#999; font-size:13px; margin:4px 0 0; }
.filter-card { margin:0 16px 16px; }
.table-card { margin:0 16px 16px; }
.add-card { background:#fff5f5; }
</style>
